version: '3.9'
services:
  api:
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      dockerfile: Dockerfile
      context: .
      target: '${NODE_ENV}'
    entrypoint: ['npm', 'run', 'start']
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - mynet
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - mynet
  redis:
    image: 'redis:alpine'
volumes:
  redis:
    driver: local
  docker-nest-postgres:
networks:
  mynet:
    name: shared-db-network
